# encoding: UTF-8

ON=1
OFF=0
UPDATE_STREAM=true
UPDATE_DAY=true


MIN_COMPETITORS=2
MAX_DATE_RANGE=92

FACEBOOK= 'facebook'
FACEBOOK_APP_ID_DEV= '1421815078052610'
FACEBOOK_APP_SECRET_DEV= 'a875d28f49fdbc647b79654d920622ac'
FACEBOOK_APP_ID= ''
FACEBOOK_APP_SECRET= ''
TWITTER= 'twitter'
TWITTER_CONSUMER_KEY= 'Tx5qMYwgzYQwfO8Q48ilg'
TWITTER_CONSUMER_SECRET= 'JLprAj48slYmthrxvcq7m2XdRf1DbYTtR6B6Mt2cVA'
YOUTUBE= 'youtube'



M_DASHBOARD = "Dashboard"
M_ENGAGEMENT = "Engagement"
M_CRECIMIENTO = "Crecimiento"
M_TAMANO = "Tamaño"
M_ACTIVIDAD = "Actividad"


FREE = 'free'
ADMIN = 'admin'
PREMIUM = 'premium_FB'
